export const INITIAL_TPS_DATA = [
  { "name": "TPS Lapangan Sidorahayu", "type": "Container", "subDistrict": "Kedaton", "address": "Jl. Kelinci", "lat": -5.385444, "lng": 105.258964, "capacity": "4 Ton", "generation": "4 Ton" },
  { "name": "TPS Sukamenanti", "type": "Container", "subDistrict": "Kedaton", "address": "Jl. Rusa", "lat": -5.391806, "lng": 105.254056, "capacity": "4 Ton", "generation": "4 Ton" },
  { "name": "TPS MBK", "type": "Container", "subDistrict": "Kedaton", "address": "Jl. Sultan Agung", "lat": -5.38235, "lng": 105.261238, "capacity": "4 Ton", "generation": "4 Ton" },
  { "name": "TPS Beringin Jaya", "type": "Tetap", "subDistrict": "Kemiling", "address": "Jl. Lapangan Kalpataru", "lat": -5.399909, "lng": 105.208606, "capacity": "16 Ton", "generation": "16,5 Ton" },
  { "name": "TPS Sumberejo", "type": "Tetap", "subDistrict": "Kemiling", "address": "Jl. Lapangan Kalpataru", "lat": -5.399909, "lng": 105.208606, "capacity": "16 Ton", "generation": "16,5 Ton" },
  { "name": "TPS Bkp", "type": "Container", "subDistrict": "Kemiling", "address": "Jl. Bu Kemiling Permai", "lat": -5.380291, "lng": 105.210396, "capacity": "16 Ton", "generation": "16,5 Ton" },
  { "name": "TPS Malahayati", "type": "Container", "subDistrict": "Kemiling", "address": "Universitas Malahayati", "lat": -5.383833, "lng": 105.218278, "capacity": "16 Ton", "generation": "16,5 Ton" },
  { "name": "TPS Garuda", "type": "Tetap", "subDistrict": "Kemiling", "address": "Jl. Garuda", "lat": -5.398735, "lng": 105.201559, "capacity": "16 Ton", "generation": "16,5 Ton" },
  { "name": "TPS Gg. Senen", "type": "Tetap", "subDistrict": "Langkapura", "address": "Gg.Senen Langkapura", "lat": -5.386426, "lng": 105.228363, "capacity": "8 Ton", "generation": "24 Ton" },
  { "name": "TPS Gantung", "type": "Gantung", "subDistrict": "Langkapura", "address": "Jl. Waspada Gunung Terang", "lat": -5.397972, "lng": 105.236724, "capacity": "8 Ton", "generation": "16 Ton" },
  { "name": "TPS PIDADA", "type": "Container", "subDistrict": "Panjang", "address": "Jl. Yos Sudarso", "lat": -5.464436, "lng": 105.318243, "capacity": "16 Ton", "generation": "15 Ton" },
  { "name": "TPS POLMAS", "type": "Container", "subDistrict": "Panjang", "address": "Jl. S. Hatta", "lat": -5.480099, "lng": 105.325836, "capacity": "8 Ton", "generation": "8 Ton" },
  { "name": "TPS KARANG MARITIM", "type": "Container", "subDistrict": "Panjang", "address": "Jl. S. Hatta", "lat": -5.485803, "lng": 105.32642, "capacity": "8 Ton", "generation": "8 Ton" },
  { "name": "TPS GRESIA", "type": "Container", "subDistrict": "Panjang", "address": "Jl. S. Hatta", "lat": -5.504382, "lng": 105.336843, "capacity": "8 Ton", "generation": "8 Ton" },
  { "name": "TPS PASAR PANJANG", "type": "Container", "subDistrict": "Panjang", "address": "Jl. Yos Sudarso Pasar Panjang", "lat": -5.472733, "lng": 105.322956, "capacity": "8 Ton", "generation": "8 Ton" },
  { "name": "TPS LINI 1", "type": "Container", "subDistrict": "Panjang", "address": "Jl. Yos Sudarso", "lat": -5.461279, "lng": 105.314991, "capacity": "8 Ton", "generation": "8 Ton" },
  { "name": "TPS LINI 2", "type": "Container", "subDistrict": "Panjang", "address": "Jl. Yos Sudarso", "lat": -5.458035, "lng": 105.314331, "capacity": "8 Ton", "generation": "8 Ton" },
  { "name": "TPS WAY LUNIK", "type": "Container", "subDistrict": "Panjang", "address": "Jl. Moh Salim", "lat": -5.44552, "lng": 105.309457, "capacity": "8 Ton", "generation": "8 Ton" },
  { "name": "TPS JAWER", "type": "Container", "subDistrict": "Panjang", "address": "Jl. Yos Sudarso", "lat": -5.431797, "lng": 105.294802, "capacity": "8 Ton", "generation": "8 Ton" },
  { "name": "TPS BELAKANG LDC", "type": "Gantung", "subDistrict": "Panjang", "address": "Jl. S. Hatta", "lat": -5.457766, "lng": 105.315375, "capacity": "6 Ton", "generation": "6 Ton" },
  { "name": "TPS KETAPANG KUALA", "type": "Gantung", "subDistrict": "Panjang", "address": "Jl. M. Salim", "lat": -5.445689, "lng": 105.30234, "capacity": "6 Ton", "generation": "6 Ton" },
  { "name": "TPS CANDI", "type": "Gantung", "subDistrict": "Panjang", "address": "Jl. S. Hatta", "lat": -5.445488, "lng": 105.313097, "capacity": "6 Ton", "generation": "6 Ton" },
  { "name": "TPS INDUK", "type": "Tetap", "subDistrict": "Rajabasa", "address": "Komplek Terminal Rajabasa", "lat": -5.366293, "lng": 105.235215, "capacity": "20 Ton", "generation": "20 Ton" },
  { "name": "TPS UNILA", "type": "Container", "subDistrict": "Rajabasa", "address": "Jl. Soekarno Hatta", "lat": -5.360893, "lng": 105.240702, "capacity": "25 Ton", "generation": "25 Ton" },
  { "name": "TPS UBL", "type": "Container", "subDistrict": "Rajabasa", "address": "Jl. Z A Pagar Alam", "lat": -5.375306, "lng": 105.2465, "capacity": "4 Ton", "generation": "4 Ton" },
  { "name": "TPS RAMAYANA", "type": "Container", "subDistrict": "Rajabasa", "address": "Jl. Z A Pagar Alam", "lat": -5.372, "lng": 105.237889, "capacity": "4 Ton", "generation": "4 ton" },
  { "name": "TPS RAJABASA NUNYAI", "type": "Container", "subDistrict": "Rajabasa", "address": "Jl. Aquarius I", "lat": -5.375133, "lng": 105.226416, "capacity": "5 Ton", "generation": "5 Ton" },
  { "name": "TPS KEPAYANG", "type": "Container", "subDistrict": "Rajabasa", "address": "Jl. Raden Gunawan II", "lat": -5.366828, "lng": 105.219755, "capacity": "5 Ton", "generation": "5 Ton" },
  { "name": "TPS RAJABASA RAYA", "type": "Gantung", "subDistrict": "Rajabasa", "address": "Komplek Terminal Rajabasa", "lat": -5.366293, "lng": 105.235215, "capacity": "7 Ton", "generation": "7 ton" },
  { "name": "TPS LP", "type": "Container", "subDistrict": "Rajabasa", "address": "Jl. Pramuka", "lat": -5.373414, "lng": 105.223474, "capacity": "5 Ton", "generation": "5 Ton" },
  { "name": "TPS Karunia Indah", "type": "Tetap", "subDistrict": "Sukabumi", "address": "Jl.Pulau bangka", "lat": -5.401667, "lng": 105.299167, "capacity": "-", "generation": "7 ton" },
  { "name": "TPS Griya Abdi Negara", "type": "Gantung", "subDistrict": "Sukabumi", "address": "Jl. Griya Abdi Negara", "lat": -5.404222, "lng": 105.319667, "capacity": "-", "generation": "7 ton" },
  { "name": "TPS Pasar Smep", "type": "Container", "subDistrict": "Tanjung Karang Barat", "address": "Jl. Kaliawi", "lat": -5.409694, "lng": 105.255111, "capacity": "8 Ton/ hari", "generation": "8 Ton/ hari" },
  { "name": "TPS Puncak Mas", "type": "Container", "subDistrict": "Tanjung Karang Barat", "address": "Jl. PB Marga Sukadanaham", "lat": -5.420694, "lng": 105.229111, "capacity": "3 Ton/ hari", "generation": "3 Ton/ hari" },
  { "name": "TPS Lembah Hijau", "type": "Container", "subDistrict": "Tanjung Karang Barat", "address": "Jl. Raden Imba kusuma Ratu No.21 Sukadana Ham", "lat": -5.411361, "lng": 105.230111, "capacity": "3 Ton/ hari", "generation": "3 Ton/ hari" },
  { "name": "TPS Gang Jeruk", "type": "TPS Gantung", "subDistrict": "Tanjung Karang Barat", "address": "Jl.Gedong Air", "lat": -5.397417, "lng": 105.243639, "capacity": "5 Ton/ hari", "generation": "5 Ton/ hari" },
  { "name": "TPS Kuripan", "type": "Container", "subDistrict": "Teluk Betung Barat", "address": "Jl. Dr. Setia Budi", "lat": -5.45011, "lng": 105.255755, "capacity": "16 Ton", "generation": "15 Ton" },
  { "name": "TPS Serpung", "type": "Container", "subDistrict": "Teluk Betung Barat", "address": "Jl.Sunda Nog", "lat": -5.443758, "lng": 105.249799, "capacity": "8 Ton", "generation": "8 Ton" },
  { "name": "TPS Batu Putuk", "type": "Container", "subDistrict": "Teluk Betung Barat", "address": "Jl.Wan Abdurrahman", "lat": -5.436582, "lng": 105.220242, "capacity": "8 Ton", "generation": "8 Ton" },
  { "name": "TPS Sukarame II", "type": "Container", "subDistrict": "Teluk Betung Barat", "address": "Jl. Morotai", "lat": -5.440051, "lng": 105.238297, "capacity": "8 Ton", "generation": "8 Ton" },
  { "name": "TPS PESAWAHAN", "type": "Container", "subDistrict": "Teluk Betung Selatan", "address": "Jl. Ekor Kuning", "lat": -5.450462, "lng": 105.261468, "capacity": "5 Ton", "generation": "5 Ton" },
  { "name": "TPS GUNUNG MAS", "type": "Container", "subDistrict": "Teluk Betung Selatan", "address": "Jl. Wr. Supratman Kel. Gunung Mas", "lat": -5.443369, "lng": 105.27082, "capacity": "2.5 Ton", "generation": "2.5 Ton" },
  { "name": "TPS PASAR CIMENG", "type": "Container", "subDistrict": "Teluk Betung Selatan", "address": "Komplek Pasar Cimeng", "lat": -5.449129, "lng": 105.256998, "capacity": "2.5 Ton", "generation": "2.5 Ton" },
  { "name": "TPS PASAR KANGKUNG", "type": "Container", "subDistrict": "Teluk Betung Selatan", "address": "Jl. Ikan Kerisi Kel. Teluk Betung", "lat": -5.446419, "lng": 105.268905, "capacity": "2.5 Ton", "generation": "2.5 Ton" },
  { "name": "TPS SD TALANG", "type": "Container", "subDistrict": "Teluk Betung Selatan", "address": "Jl.Ikan Mujair", "lat": -5.446650, "lng": 105.257179, "capacity": "2 Ton", "generation": "2 Ton" },
  { "name": "TPS KEL. TALANG", "type": "Tetap", "subDistrict": "Teluk Betung Selatan", "address": "Jl. Wr. Supratman Kel. Talang", "lat": -5.445542, "lng": 105.259197, "capacity": "500 M3", "generation": "400 M3" },
  { "name": "TPS UMBUL LABAN", "type": "Tetap", "subDistrict": "Teluk Betung Selatan", "address": "Jl. P. Emir M.Noer", "lat": -5.430011, "lng": 105.242776, "capacity": "300 M3", "generation": "200 M3" },
  { "name": "TPS TAMAN DIPANGGA", "type": "Tetap", "subDistrict": "Teluk Betung Selatan", "address": "Jl. Jaksa R. Suprapto", "lat": -5.445547, "lng": 105.261443, "capacity": "300 M3", "generation": "200 m3" },
  { "name": "KOTA KARANG RAYA", "type": "TPS Gantung", "subDistrict": "Teluk Betung Timur", "address": "Jl. RE. Martadinata", "lat": -5.457639, "lng": 105.254528, "capacity": "-", "generation": "8 Ton" },
  { "name": "TPS WAY TATAAN", "type": "TPS Gantung", "subDistrict": "Teluk Betung Timur", "address": "Jl. TPI Lempasing", "lat": -5.486889, "lng": 105.251556, "capacity": "-", "generation": "8 Ton" },
  { "name": "TPS DWI SARTIKA", "type": "Container", "subDistrict": "Teluk Betung Utara", "address": "Jl. DEWI SARTIKA", "lat": -5.432767, "lng": 105.259444, "capacity": "4 Ton", "generation": "4 Ton" },
  { "name": "TPS MASJID AL'FURQON", "type": "Container", "subDistrict": "Teluk Betung Utara", "address": "Jl. DIPONEGORO", "lat": -5.428901, "lng": 105.260063, "capacity": "4 Ton", "generation": "4 Ton" },
  { "name": "TPS BEGADANG RESTO", "type": "Container", "subDistrict": "Teluk Betung Utara", "address": "Jl. Sultan Agung", "lat": -5.439748, "lng": 105.265380, "capacity": "4 Ton", "generation": "4 Ton" },
  { "name": "TPS Perumnas Way halim", "type": "Container", "subDistrict": "Way Halim", "address": "Jl. Rajabasa Raya", "lat": -5.377097, "lng": 105.274806, "capacity": "1 Container", "generation": "10 ton / Hari" },
  { "name": "TPS Dom", "type": "Container", "subDistrict": "Way Halim", "address": "Jl. Morotai", "lat": -5.399465, "lng": 105.277972, "capacity": "1 Container", "generation": "5 Ton/ Hari" },
  { "name": "TPS Kali Raman", "type": "Container", "subDistrict": "Way Halim", "address": "Jl. Pulau Seram Jagabaya", "lat": -5.405522, "lng": 105.267966, "capacity": "1 Container", "generation": "5 Ton/ Hari" },
  { "name": "TPS PKOR", "type": "TPS Gantung", "subDistrict": "Way Halim", "address": "Jalur 2 Mie Aceh PKOR", "lat": -5.380399, "lng": 105.280622, "capacity": "2 Dumtruck", "generation": "10 ton / Hari" },
  { "name": "TPS Villa Citra", "type": "Container", "subDistrict": "Way Halim", "address": "Jl. H. Said", "lat": -5.401972, "lng": 105.274287, "capacity": "1 Container", "generation": "5 Ton/ Hari" },
  { "name": "TPS KEPAYANG", "type": "Tetap", "subDistrict": "Bumi Waras", "address": "JL. YOS SUDARSO GG. IKAN SELAR", "lat": -5.450818, "lng": 0, "capacity": "20 Ton", "generation": "20 Ton" },
  { "name": "TPS NILA KANDI", "type": "Tetap", "subDistrict": "Bumi Waras", "address": "JL. NILA RAYA GG SAHADI HASAN", "lat": -5.438015, "lng": 0, "capacity": "12 Ton", "generation": "12 Ton" },
  { "name": "TPS PEKULITAN", "type": "Container", "subDistrict": "Bumi Waras", "address": "JL. IKAN DUYUNG", "lat": -5.444793, "lng": 0, "capacity": "12 Ton", "generation": "12 Ton" },
  { "name": "TPS GUDANG LELANG", "type": "Container", "subDistrict": "Bumi Waras", "address": "JL. IKAN BAWAL PASAR GUDEL", "lat": -5.44436, "lng": 0, "capacity": "16 Ton", "generation": "16 Ton" },
  { "name": "TPS Belakang Polsek Tanjung senang", "type": "Container", "subDistrict": "Tanjung Seneng", "address": "JL. bunga Raflesia No 25", "lat": -5.362161, "lng": 105.283315, "capacity": "24 Ton", "generation": "24 Ton" },
  { "name": "TPS KOTA BARU", "type": "CONTAINER", "subDistrict": "Tanjung Karang Timur", "address": "JL.DOKTER HARUN 1", "lat": -5.415585, "lng": 105.271965, "capacity": "12 TON", "generation": "12 TON" },
  { "name": "TPS PASAR TUGU", "type": "CONTAINER", "subDistrict": "Tanjung Karang Timur", "address": "JL HAYAM WURUK", "lat": -5.409442, "lng": 105.265888, "capacity": "18 TON", "generation": "18 TON" },
  { "name": "TPS Jalur 2 UIN", "type": "TPS Gantung", "subDistrict": "Sukarame", "address": "Jl. Pulau Sebesi, Kel. Sukarame, Kec. Sukarame", "lat": -5.636944, "lng": 105.516833, "capacity": "8 TON", "generation": "8 TON" },
  { "name": "TPS ABC", "type": "Countainer", "subDistrict": "Tanjung Karang Pusat", "address": "Jl. Cut Nyak Dien", "lat": -5.414842, "lng": 105.246642, "capacity": "5 TON", "generation": "7 TON" },
  { "name": "TPS PS. TAMIN", "type": "Countainer", "subDistrict": "Tanjung Karang Pusat", "address": "JL. Tamin", "lat": -5.411301, "lng": 105.247449, "capacity": "5 TON", "generation": "7 TON" },
  { "name": "TPS HANOMAN", "type": "Countainer", "subDistrict": "Tanjung Karang Pusat", "address": "Jl. Hanoman", "lat": -5.404245, "lng": 105.260773, "capacity": "4 TON", "generation": "5 TON" },
  { "name": "TPS RAMAYANA", "type": "Countainer", "subDistrict": "Tanjung Karang Pusat", "address": "Jl. Pemuda", "lat": -5.411355, "lng": 105.259152, "capacity": "5 TON", "generation": "6 TON" }
];
